name: BMCPlugin
main: xyz.hinyari.bmcplugin.BMCPlugin
version: 1.2.8
author: Hinyari_Gohan
description: Bukkit Plugin for BMCServer.
softdepend: [Essentials, Votifier. PermissionsEX]
commands:
  bmc:
    description: bmcコマンドです
  rank:
    description: BMCランクに関する情報を表示します。
  rankup:
    description: ランクアップを可能にします。
  kome:
    description: BMC米に関する情報を表示します。
  cop:
    description: デバッグ用・OP権限の有無を変更します。
  guiedit:
    description: GUI作成支援GUIを表示します。
  nikkei:
    description: 日経平均株価を取得します。
  spawn:
    description: スポーン地点へ戻ります。
  broadcast:
    description: ブロードキャストします。
permissions:
  bmc.debug:
    description: デバッグ用のコマンドの使用権限
    default: op
    permissions-message: You don''t have permission to access this command!
  bmc.acrobat:
    description: アクロバットキットの使用権限
    default: op
  bmc.scout.get:
    description: スカウトキットの使用権限
    default: op
  ntp.kick:
    description: NoTaisukePlusのキックの使用権限
    default: op
  bmc.vanish:
    default: op
  bmc.vanish.notice:
    default: op
  bmc.permmsg:
    default: op
  bmc.rankmenu:
    default: true
  bmc.rankmenu.get:
    default: op
  bmc.rank.set:
    default: op
  bmc.nclv:
    default: op
  bmc.admin:
    children:
      plugin.debug: true
      plugin.scout.get: true
  bmc.vote:
    default: op
  bmc.kome.admin:
    default: op
  bmc.kome.give:
    default: op
  bmc.broadcast:
    default: op
  bmc.halfblock:
    default: op
