name: BMCPlugin
main: com.github.gotochan.BMC
version: 4.0
author: Hinyari_Gohan
description: BMCPlugin
commands:
  bmc:
    description: bmcコマンドです。
    aliases: []
permissions:
  bmc.debug:
    description: デバッグ用のコマンドの使用権限
    default: op
    permissions-message: You don''t have permission to access this command!