name: BMCPlugin
main: xyz.hinyari.bmcplugin.BMCPlugin
version: 1.0.0
author: Hinyari_Gohan
description: The plugin for BMCServer.
softdepend: [Essentials]
commands:
  plugin:
    description: bmcコマンドです。
    aliases: []
  rank:
  rankup:
  kome:
  cop:
permissions:
  plugin.debug:
    description: デバッグ用のコマンドの使用権限
    default: op
    permissions-message: You don''t have permission to access this command!
  plugin.acrobat:
    description: アクロバットキットの使用権限
    default: op
  plugin.scout.get:
    description: スカウトキットの使用権限
    default: op
  ntp.kick:
    description: NoTaisukePlusのキックの使用権限
    default: op
  plugin.vanish:
    default: op
  plugin.vanish.notice:
    default: op