name: BMCPlugin
main: com.github.gotochan.BMC
version: 3.0
author: Hinyari_Gohan
description: BMC'sPlugin - koshihikari
commands:
  koshihikari:
    description: コシヒカリに関するコマンドです。
    permission: bmc.kome
    permission-message: このコマンドを実行する権限がありません。
    aliases: [koshi, kome]
  rank:
    description: ランクに関するコマンドです。
    permission: bmc.kome
    permission-message: このコマンドを実行する権限がありません。
    aliases: [ranks,koshihikarirank,bmcrank]