name: BMCPlugin
main: com.github.gotochan.BMC
version: 4.0
author: Hinyari_Gohan
description: BMCPlugin
commands:
  bmc:
    description: bmcコマンドです。
    aliases: []
  rank:
  rankup:
  kome:
  ntp:
    description: NoTaisukePlusのコマンドです。
    aliases: [notaisukeplus]
permissions:
  bmc.debug:
    description: デバッグ用のコマンドの使用権限
    default: op
    permissions-message: You don''t have permission to access this command!
  bmc.acrobat:
    description: アクロバットキットの使用権限
    default: op
  bmc.scout.get:
    description: スカウトキットの使用権限
    default: op
  ntp.kick:
    description: NoTaisukePlusのキックの使用権限
    default: op