name: BMCPlugin
main: com.github.gotochan.BMC
version: 2.1
author: Attaka_Gohan
description: BMC
commands:
  koshihikari:
    description: コシヒカリ交換チケット数を参照するコマンドです。
    permission: bmc.kome
    permission-message: このコマンドを実行する権限がありません。
    aliases: [koshi, kome]
  rank:
    description: rank
    permission: bmc.rank
    permission-message: このコマンドを実行する権限がありません。
    aliases: [ranks, ranksystem]